---
- include_tasks: ../../../includes/lotus_general_runtime_deps.yml

- name: Ensure stelegraf group
  group:
    name: stelegraf
    system: yes

- name: Ensure stelegraf user
  user:
    name: stelegraf
    group: stelegraf
    system: yes

- name: Copy stelegraf binary
  copy:
    src: "{{ sentinel_telegraf_binary_src }}"
    dest: /usr/local/bin/stelegraf
    owner: root
    group: root
    mode: "0755"
  when: sentinel_telegraf_binary_src is defined
  notify:
    - restart_stelegraf

- name: Ensure stelegraf configuration directory
  file:
    name: /etc/stelegraf
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure stelegraf configuration directory
  file:
    name: /etc/stelegraf/stelegraf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

# TODO(tperson): source from sentinel repo
- name: Copy stelegraf configuration template to hosts
  template:
    src: templates/stelegraf.conf.j2
    dest: /etc/stelegraf/stelegraf.conf
    mode: '0644'
  notify:
    - restart_stelegraf

- name: Copy stelegraf logrotate configuration
  copy:
    src: files/etc/logrotate.d/stelegraf
    dest: /etc/logrotate.d/stelegraf
    mode: '0644'

- name: Ensure stelegraf log directory
  file:
    name: /var/log/stelegraf
    state: directory
    owner: stelegraf
    group: stelegraf
    mode: '0755'

- name: Ensure systemd file
  copy:
    src: files/lib/systemd/system/stelegraf.service
    dest: /lib/systemd/system/stelegraf.service
    mode: '0644'


- name: Ensure stelegraf started and enabled
  systemd:
    name: stelegraf
    daemon_reload: yes
    state: started
    enabled: yes
