- name: Ensure drand key is imported
  block:
    - name: Verify drand_id_private is defined
      fail: msg="drand_id_private is not defined"
      when: drand_id_private is not defined
    - name: Verify drand_id_public is defined
      fail: msg="drand_id_public is not defined"
      when: drand_id_public is not defined
    - name: Verify drand_generate_keypair is false
      fail: msg="drand_generate_keypair must be false to import key"
      when: drand_generate_keypair == true
    - name: Ensure key path created
      file:
        path: "{{ drand_path }}/key/"
        state: directory
        owner: "{{ drand_user }}"
        group: "{{ drand_user }}"
        mode: "0700"
    - name: Ensure private key exists
      copy:
        content: "{{ drand_id_private }}"
        owner: "{{ drand_user }}"
        group: "{{ drand_user }}"
        mode: "0600"
        dest: "{{ drand_path }}/key/drand_id.private"
    - name: Ensure public key exists
      copy:
        content: "{{ drand_id_public }}"
        owner: "{{ drand_user }}"
        group: "{{ drand_user }}"
        mode: "0600"
        dest: "{{ drand_path }}/key/drand_id.public"
