- include_tasks: ../../../includes/required_vars.yml

- name: Copy binary
  copy:
    src: "{{ drand_binary_src }}"
    dest: /usr/local/bin/drand
    owner: root
    group: root
    mode: "0755"
  when: drand_binary_src is defined

- name: Reset system
  block:
    - name: Ensure drand stopped
      service:
        name: drand
        state: stopped
    - name: Remove drand repository
      file:
        path: "{{ drand_path }}"
        state: absent
  when: drand_reset == "yes"

- name: Ensure drand repository exists
  file:
    path: "{{ drand_path }}"
    state: directory
    owner: "{{ drand_user }}"
    group: "{{ drand_user }}"
    mode: "0740"

- name: Import keypair
  include_tasks: import_keys.yml
  when: drand_import_keypair | bool

- name: Generate keypair
  shell:
    cmd: drand generate-keypair --folder {{ drand_path }} --tls-disable={{ drand_public_tls_disable | lower }} {{ drand_public_host }}:{{ drand_public_port }}
    creates: "{{ drand_path }}/key/drand_id.private"
  become: yes
  become_user: "{{ drand_user }}"
  when: drand_generate_keypair | bool

- name: Ensure service file
  template:
    src: ../templates/drand.service.j2
    dest: /etc/systemd/system/drand.service
    owner: root
    group: root
    mode: "0644"

- name: Ensure drand service enabled and in correct state ({{ drand_service_state }})
  service:
    name: "drand"
    enabled: yes
    state: "{{ drand_service_state }}"

- name: Ensure certbot certificate
  command: certbot certonly -d {{ drand_public_host }} --non-interactive --agree-tos -m infra-accounts@protocol.ai --nginx
  when: drand_run_certbot | bool

- name: Ensure drand nginx site is available
  template:
    src: ../templates/drand-https.conf.j2
    dest: /etc/nginx/sites-available/drand.conf
    mode: 0644

- name: Ensure drand nginx site is enabled
  file:
    src: /etc/nginx/sites-available/drand.conf
    path: /etc/nginx/sites-enabled/drand.conf
    state: link
  notify: reload_nginx

- set_fact:
    drand_telegraf_tags: {}

- set_fact:
    drand_telegraf_inputs_procstat:
      - "drand"
