---
- name: Add telegraf apt key
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"

- name: Add telegraf apt repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu disco stable"
    state: present

- name: Update repositories cache and install "telegraf" package
  apt:
    name: telegraf
    update_cache: yes

- name: Ensure telegraf started and enabled
  systemd:
    name: telegraf
    state: started
    enabled: yes

- set_fact:
    telegraf_global_tags: "{{ telegraf_global_tags | combine(item) }}"
  loop: "{{ telegraf_global_tag_groups }}"

- name: Copy telegraf configuration template to hosts
  template:
    src: templates/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: '0644'
  notify:
    - restart_telegraf
