---
deployments:
  # efs access
  - chart: filecoin/efs-access
    version: 0.1.0
    namespace: ntwk-mainnet-fullnode
    name: efs-access
    values:
      - efs-access
  - chart: filecoin/efs-access
    version: 0.1.0
    namespace: ntwk-mainnet-bootstrap
    name: efs-access
    values:
      - efs-access
  # fullnodes
  - chart: filecoin/lotus-fullnode
    version: 0.1.11
    namespace: ntwk-mainnet-fullnode
    name: fullnode-0
    values:
      - base
  - chart: filecoin/lotus-fullnode
    version: 0.1.11
    namespace: ntwk-mainnet-fullnode
    name: fullnode-1
    values:
      - base
  - chart: filecoin/lotus-fullnode
    version: 0.1.11
    namespace: ntwk-mainnet-fullnode
    name: fullnode-2
    values:
      - base
  - chart: filecoin/lotus-fullnode
    version: 0.1.11
    namespace: ntwk-mainnet-fullnode
    name: fullnode-3
    values:
      - base
      - from-snapshot
  # bootstrap
  - chart: filecoin/lotus-fullnode
    version: 0.1.11
    namespace: ntwk-mainnet-bootstrap
    name: bootstrap-0
    values:
      - base
      - bootstrap-0
  - chart: filecoin/lotus-fullnode
    version: 0.1.11
    namespace: ntwk-mainnet-bootstrap
    name: bootstrap-1
    values:
      - base
      - bootstrap-1
  - chart: filecoin/lotus-fullnode
    version: 0.1.11
    namespace: ntwk-mainnet-bootstrap
    name: bootstrap-2
    values:
      - base
      - bootstrap-2
  # consensus check
  - chart: filecoin/lotus-consensus-check
    version: 0.1.1
    namespace: ntwk-mainnet-bootstrap
    name: cc-common
    values:
      - cc-common
  - chart: filecoin/lotus-consensus-check
    version: 0.1.1
    namespace: ntwk-mainnet-fullnode
    name: cc-common
    values:
      - cc-common
