apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ntwk-calibrationnet

resources:
- ../../common
- ../../../base/images/lotus/calibrationnet
- flux-tenant.yaml
- flux-kustomization.yaml
- flux-image-update-automation.yaml
