- name: Debug - Show lotus_user value
  debug:
    var: lotus_user

- name: Debug - Show lotus_user_uid value
  debug:
    var: lotus_user_uid

- name: Ensure lotus group exists
  group:
    name: "{{ lotus_user }}"
    state: present
    gid: "{{ lotus_user_uid }}"
  become: yes

- name: Ensure lotus user exists
  user:
    name: "{{ lotus_user }}"
    state: present
    uid: "{{ lotus_user_uid }}"
    group: "{{ lotus_user }}"
    system: yes
  become: yes

- name: Get groups for ansible_user
  command: "groups {{ ansible_user }}"
  register: user_groups
  changed_when: false
  check_mode: no

- name: Debug - Show user_groups result
  debug:
    var: user_groups

- name: Debug - Show group_check result
  debug:
    var: group_check

- name: Debug - Show all groups
  command: "getent group"
  register: all_groups
  changed_when: false
  check_mode: no

- name: Debug - Show all groups
  debug:
    var: all_groups.stdout_lines

- name: Ensure login user is added to lotus group
  user:
    name: "{{ ansible_user }}"
    groups: "{{ lotus_user }}"
    append: yes
  become: yes
  when: lotus_user not in user_groups.stdout.split()

