- name: Ensure lotus group exists
  group:
    name: "{{ lotus_user }}"
    state: present
    gid: "{{ lotus_user_uid }}"

- name: Ensure lotus user exists
  user:
    name: "{{ lotus_user }}"
    state: present
    uid: "{{ lotus_user_uid }}"
    group: "{{ lotus_user }}"
    system: yes

- name: Get groups for ansible_user
  command: "groups {{ ansible_user }}"
  register: user_groups
  changed_when: false
  check_mode: no

- name: Verify lotus group exists
  command: "getent group {{ lotus_user }}"
  register: group_check
  changed_when: false
  failed_when: false
  check_mode: no

- name: Debug - Show group_check result
  debug:
    var: group_check

- name: Debug - Show all groups
  command: "getent group"
  register: all_groups
  changed_when: false
  check_mode: no

- name: Debug - Show all groups
  debug:
    var: all_groups.stdout_lines

- name: Ensure login user is added to lotus group
  user:
    name: "{{ ansible_user }}"
    groups: "{{ lotus_user }},{{ user_groups.stdout.split() | join(',') }}"
    append: yes
  when: lotus_user not in user_groups.stdout.split()

