image:
  tag: calibnet-v1.18.0-rc5

prometheusOperatorServiceMonitor: true

secrets:
  jwt:
    enabled: true
    secretName: lotus-jwt

resources:
  requests:
    memory: 8Gi

importSnapshot:
  enabled: true
  strategy: url
  url: https://snapshots.calibrationnet.filops.net/minimal/latest

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]

additionalLabels:
  network: calibrationnet

persistence:
  datastore:
    enabled: true
    easyReset: true
    storageClassName: "gp2"
    size: "500Gi"
