- include_tasks: ../../../includes/required_vars.yml
- include_tasks: ../../../includes/lotus_general_runtime_deps.yml

- name: Ensure dependencies are installed
  package:
    name:
      - numactl

- name: Ensure ntp is started
  service:
    name: ntp
    enabled: yes
    state: started

- name: Copy lotus-seed binary
  copy:
    src: "{{ lotus_seed_binary_src }}"
    dest: /usr/local/bin/lotus-seed
    owner: root
    group: root
    mode: "0755"
  when: lotus_seed_binary_src is defined

- name: Creating seed workers
  include_tasks: worker.yml
  loop: "{{ lotus_seed_workers }}"

- set_fact:
    lotus_seed_filebeat_input:
      paths: "{{ lotus_seed_workers | map(attribute='log_file') | list }}"
      fields:
        type: "lotus-seed"
