---
all:
  children:
    packet:
      vars:
        ansible_user: root
      children:
        lotus_bootstrap:
          hosts:
            # bootstrap-0-sin.fil-test.net:
            bootstrap-0-dfw.fil-test.net:
            bootstrap-0-fra.fil-test.net:
            # bootstrap-1-sin.fil-test.net:
            bootstrap-1-dfw.fil-test.net:
            bootstrap-1-fra.fil-test.net:
        faucet:
          hosts:
            fountain.fil-test.net:
        stats:
          hosts:
            stats.fil-test.net:
        sentinel:
          hosts:
            sentinel.fil-test.net:

    aws:
      vars:
        ansible_user: ubuntu
      children:
        presealed_miners:
          hosts:
            t01000.miner.fil-test.net:
            t01001.miner.fil-test.net:
            t01002.miner.fil-test.net:
        presealed_miners_all:
          hosts:
            t01000.miner.fil-test.net:
            t01001.miner.fil-test.net:
            t01002.miner.fil-test.net:
        presealers:
          hosts:
            t01000w0.seeder.fil-test.net:
            t01000w1.seeder.fil-test.net:
            t01000w2.seeder.fil-test.net:
            t01000w3.seeder.fil-test.net:
            t01000w4.seeder.fil-test.net:
            t01000w5.seeder.fil-test.net:
            t01001w0.seeder.fil-test.net:
            t01001w1.seeder.fil-test.net:
            t01001w2.seeder.fil-test.net:
            t01001w3.seeder.fil-test.net:
            t01001w4.seeder.fil-test.net:
            t01001w5.seeder.fil-test.net:
            t01002w0.seeder.fil-test.net:
            t01002w1.seeder.fil-test.net:
            t01002w2.seeder.fil-test.net:
            t01002w3.seeder.fil-test.net:
            t01002w4.seeder.fil-test.net:
            t01002w5.seeder.fil-test.net:
    lotus_daemon:
      children:
        presealed_miners:
        lotus_bootstrap:
        faucet:
        stats:
        sentinel:

    chainwatch:
      children:
        stats:

    t01000:
      hosts:
        t01000.miner.fil-test.net:
        t01000w0.seeder.fil-test.net:
        t01000w1.seeder.fil-test.net:
        t01000w2.seeder.fil-test.net:
        t01000w3.seeder.fil-test.net:
        t01000w4.seeder.fil-test.net:
        t01000w5.seeder.fil-test.net:

    t01001:
      hosts:
        t01001.miner.fil-test.net:
        t01001w0.seeder.fil-test.net:
        t01001w1.seeder.fil-test.net:
        t01001w2.seeder.fil-test.net:
        t01001w3.seeder.fil-test.net:
        t01001w4.seeder.fil-test.net:
        t01001w5.seeder.fil-test.net:

    t01002:
      hosts:
        t01002.miner.fil-test.net:
        t01002w0.seeder.fil-test.net:
        t01002w1.seeder.fil-test.net:
        t01002w2.seeder.fil-test.net:
        t01002w3.seeder.fil-test.net:
        t01002w4.seeder.fil-test.net:
        t01002w5.seeder.fil-test.net:
