version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  helm: circleci/helm@1.2.0

commands:
  install-helm:
    steps:
      - helm/install-helm-client:
          version: v3.5.0
  install-helm-repos:
    steps:
      - run:
          command: |
            helm repo add filecoin https://filecoin-project.github.io/helm-charts
  setup-eks:
      parameters:
        cluster:
          type: string
          default: ${cluster}
          description: eks cluster
        region:
          type: string
          default: ${region}
          description: aws region
      steps:
        - aws-eks/install-aws-iam-authenticator
        - aws-eks/update-kubeconfig-with-authenticator:
            install-kubectl: true
            cluster-name: <<parameters.cluster>>
            aws-region: <<parameters.region>>

jobs:
  lotus-deploy:
      parameters:
        cluster:
          type: string
          default: ${cluster}
          description: eks cluster
        region:
          type: string
          default: ${region}
          description: aws region
        namespace:
          type: string
          default: ${namespace}
          description: kubernetes namespace
      executor: aws-eks/python3
      steps:
        - setup-eks:
            cluster: <<parameters.cluster>>
            region: <<parameters.region>>
        - install-helm
        - install-helm-repos
        - checkout
        - run:
            name: deploy butterfly fullnodes
            command: |
              helm -n <<parameters.namespace>> list
              echo test test test
              sleep 600

workflows:
  butterfly-nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - /^(main|master)$/
    jobs:
      - lotus-butterfly
