version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  helm: circleci/helm@1.2.0

commands:
  install-helm:
    steps:
      - helm/install-helm-client:
          version: v3.5.0
  install-helm-repos:
    steps:
      - run:
          command: |
            helm repo add filecoin https://filecoin-project.github.io/helm-charts
  setup-eks:
    parameters:
      cluster:
        type: string
        description: eks cluster
      region:
        type: string
        description: aws region
    steps:
      - aws-eks/install-aws-iam-authenticator
      - aws-eks/update-kubeconfig-with-authenticator:
          install-kubectl: true
          cluster-name: <<parameters.cluster>>
          aws-region: <<parameters.region>>
  git-pull:
    parameters:
      repo:
        type: string
        description: repo url
      where:
        type: string
        description: where to save
    steps:
      - run:
          command: git pull << parameters.repo >> << parameters.where >>
  docker-login:
    steps:
      - run:
          command: echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --passwd-stdin


jobs:
  # build and push lotus.
  lotus-build-containers:
    parameters:
      tag:
        type: string
        description: lotus tag to checkout
      repo:
        type: string
        description: docker repository
      network:
        type: string
        description: filecoin network
    executor: docker
    steps:
      - checkout
      - docker-login
      - git-pull:
          repo: https://github.com/filecoin-project/lotus
          where: $HOME/lotus
      - run:
          command: scripts/build_containers.bash --src $HOME/lotus --network << parameters.network >> --tag << parameters.tag >> --docker-tag << parameters.network >>-<< parameters.tag >> --repo << parameters.repo >>

  # This will deploy a helm chart with values stored in this repo.
  # Each release will have two helm values files -- "base.yaml" and <release_name>.yaml
  # and they must be installed in the right directory in this repo.
  helm-deploy:
    parameters:
      cluster:
        type: string
        description: eks cluster name
      region:
        type: string
        description: aws region
      namespace:
        type: string
        description: kubernetes namespace
      release:
        type: string
        description: helm release
      chart:
        type: string
        description: helm chart
      chart_version:
        type: string
        description: helm chart version
    executor: aws-eks/python3
    steps:
      - checkout
      - setup-eks:
          cluster: << parameters.cluster >>
          region: << parameters.region >>
      - install-helm
      - install-helm-repos
      - run:
          name: deploy << parameters.chart >>/<< parameters.release >> to << parameters.cluster >>/<< parameters.namespace >>
          command: helm --namespace << parameters.namespace >> upgrade --install << parameters.release >> << parameters.chart >> --version << parameters.chart_version >> --values kubernetes/<< parameters.cluster >>/helm/<< parameters.namespace >>/<< parameters.chart >>/base.yaml --values kubernetes/<< parameters.cluster >>/helm/<< parameters.namespace >>/<< parameters.chart >>/<< parameters.release >>.yaml

workflows:
  nightly:
    # triggers:
    #   - schedule:
    #       cron: "0 0 * * *"
    #       filters:
    #         branches:
    #           only:
    #             - /^(main|master)$/
    jobs:
      - lotus-build-containers:
        tag: master
        repo: coryschwartz
        matrix:
          parameters:
            network:
              - mainnet
              - nerpanet
              - calibnet
              - butterflynet

      - helm-deploy:
          context: sentinel-staging-deploy
          cluster: mainnet-us-east-2-dev-eks
          region: us-east-2
          namespace: ntwk-butterfly-fullnode
          chart: filecoin/lotus-fullnode
          chart_version: 0.3.1
          matrix:
            parameters:
              release:
                - fullnode-0
                - fullnode-1
                - fullnode-2
