version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  helm: circleci/helm@1.2.0

commands:
  install-helm:
    steps:
      - helm/install-helm-client:
          version: v3.5.0
  install-helm-repos:
    steps:
      - run:
          command: |
            helm repo add filecoin https://filecoin-project.github.io/helm-charts
  setup-eks:
      parameters:
        cluster:
          type: string
          default: ${cluster}
          description: eks cluster
        region:
          type: string
          default: ${region}
          description: aws region
      steps:
        - aws-eks/install-aws-iam-authenticator
        - aws-eks/update-kubeconfig-with-authenticator:
            install-kubectl: true
            cluster-name: <<parameters.cluster>>
            aws-region: <<parameters.region>>

jobs:
  helm-deploy:
    parameters:
      cluster:
        type: string
        description: eks cluster name
      region:
        type: string
        description: aws region
      namespace:
        type: string
        description: kubernetes namespace
      release:
        type: string
        description: helm release
      chart:
        type: string
        description: helm chart
      chart_version:
        type: string
        description: helm chart version
    executor: aws-eks/python3
    steps:
      - checkout
      - setup-eks:
          cluster: << parameters.cluster >>
          region: << parameters.region >>
      - install-helm
      - install-helm-repos
      - run:
          name: deploy << parameters.chart >>/<< parameters.release >> to << parameters.cluster >>/<< parameters.namespace >>
          command: |
            helm --namespace << parameters.namespace >> upgrade --install << parameters.release >> << parameters.chart >> --version << parameters.chart_version >> --values kubernetes/<< parameters.cluster >>/helm/<< parameters.namespace >>/<< parameters.chart >>/base.yaml --values kubernetes/<< parameters.cluster >>/helm/<< parameters.namespace >>/<< parameters.chart >>/<< parameters.release >>.yaml

workflows:
  butterfly-nightly:
    # triggers:
    #   - schedule:
    #       cron: "0 0 * * *"
    #       filters:
    #         branches:
    #           only:
    #             - /^(main|master)$/
    jobs:
      - helm-deploy:
          context: sentinel-staging-deploy
          cluster: mainnet-us-east-2-dev-eks
          region: us-east-2
          namespace: ntwk-butterfly-fullnode
          chart: filecoin/lotus-fullnode
          chart_version: 0.3.1
          matrix:
            parameters:
              release:
                - fullnode-0
                - fullnode-1
                - fullnode-2
