---
deployments:
  # bootstrap
  - chart: filecoin/lotus-fullnode
    version: 0.3.4
    namespace: ntwk-mainnet-bootstrap
    name: bootstrap-6
    values:
      - base
      - bootstrap-6
  - chart: filecoin/lotus-fullnode
    version: 0.3.4
    namespace: ntwk-mainnet-bootstrap
    name: bootstrap-7
    values:
      - base
      - bootstrap-7
  - chart: filecoin/lotus-fullnode
    version: 0.3.4
    namespace: ntwk-mainnet-bootstrap
    name: bootstrap-8
    values:
      - base
      - bootstrap-8
  # disputer
  - chart: filecoin/lotus-fullnode
    version: 0.3.1
    namespace: ntwk-mainnet-disputer
    name: disputer-2
    values:
      - base
      - disputer-2
  # efs access
  - chart: filecoin/efs-access
    version: 0.1.0
    namespace: ntwk-mainnet-disputer
    name: efs-access
    values:
      - efs-access
  - chart: filecoin/efs-access
    version: 0.1.0
    namespace: ntwk-mainnet-bootstrap
    name: efs-access
    values:
      - efs-access
  # ipfs gateway monitor
  - chart: filecoin/lotus-bundle
    version: 0.0.12
    namespace: ipfs-gateway-monitor
    name: gateway-monitor
    values:
      - base
      - gateway-monitor-0
