---
image:
  repository: travisperson/lotus-gateway
  tag: mainnet-v1.10.0

ingress:
  enabled: false
  host: api.chain.love

loadBalancer:
  enabled: true
  rpcPort: 80

gatewayEnvs:
  - name: GOLOG_LOG_FMT
    value: json

deployment:
  replicas: 2

