apiVersion: v1
kind: PersistentVolume
metadata:
  name: chain-archives
spec:
  capacity:
    storage: 4096Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    # NOTE! You must provide this value
    volumeHandle: ${ efs.id }
