apiVersion: v1
kind: PersistentVolume
metadata:
  # This name should match that of the name of the storageClassName
  name: efs
spec:
  capacity:
    storage: 4096Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    # NOTE! You must provide this value.
    # Due to the way efs works with k8s, this pv only needs to be created
    # once per cluster.
    volumeHandle:
