apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name should match that of the name of the storageClassName
  name: efs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 4096Gi
