image:
  tag: v1.1.3

resources:
  requests:
    memory: 96Gi
    cpu: 8
  limits:
    memory: 112Gi
    cpu: 16

importSnapshot:
  enabled: false
  claimName: chain-exports
  network: mainnet
  exportRelease: export-full-archive
  exitCodeOnMissing: 0

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]
    BootstrapPeers = [
      "/dns4/bootstrap-0-lotus-daemon.ntwk-mainnet-bootstrap.svc.cluster.local/tcp/1347/p2p/12D3KooWCVe8MmsEMes2FzgTpt9fXtmCY7wrq91GRiaC8PHSCCBj",
      "/dns4/bootstrap-1-lotus-daemon.ntwk-mainnet-bootstrap.svc.cluster.local/tcp/1347/p2p/12D3KooWCwevHg1yLCvktf2nvLu7L9894mcrJR4MsBCcm4syShVc",
      "/dns4/bootstrap-2-lotus-daemon.ntwk-mainnet-bootstrap.svc.cluster.local/tcp/1347/p2p/12D3KooWEWVwHGn2yR36gKLozmb4YjDJGerotAPGxmdWZx2nxMC4"
    ]
    ConnMgrLow = 2

additionalLabels:
  mode: open
  network: mainnet

nodeSelector:
  mode: restricted

persistence:
  datastore:
    enabled: true
    storageClassName: "ebs-csi"
    size: "2000Gi"
