secrets:
  libp2p:
    enabled: true
    secretName: fullnode-7-libp2p-secrets
    libp2p_key: libp2p-host
  jwt:
    enabled: true
    secretName: fullnode-7-jwt-secrets

importSnapshot:
  enabled: true
  claimName: chain-exports
  network: mainnet
  exportRelease: finality-stateroots
  exitCodeOnMissing: 1

resources:
  requests:
    memory: 100Gi

persistence:
  datastore:
    enabled: true
    storageClassName: "ebs-csi"
    size: "8000Gi"
