image:
  repository: coryschwartz/lotus
  tag: mainnet-7e25a811c

secrets:
  libp2p:
    enabled: true
    secretName: fullnode-7-libp2p-secrets
    libp2p_key: libp2p-host
  jwt:
    enabled: true
    secretName: fullnode-7-jwt-secrets

importSnapshot:
  enabled: true
  claimName: chain-exports
  network: mainnet
  exportRelease: finality-stateroots
  exitCodeOnMissing: 1

resources:
  requests:
    memory: 100Gi
