---
logz_io_shared_token: "{{ vault_logz_io_shared_token }}"
telegraf_global_tags: {}
# influx monitoring options
telegraf_outputs_influxdb_enabled: true
telegraf_outputs_influxdb_username: lotus
telegraf_outputs_influxdb_password: "{{ vault_influxdb_lotus_password }}"
telegraf_outputs_influxdb_database: lotus-nodes
telegraf_outputs_influxdb_url: https://eightyeight-1b1e0a69.influxcloud.net:8086

# Sentinel monitoring options
telegraf_outputs_postgresql_enabled: false
telegraf_inputs_lotus_enabled: false
telegraf_inputs_prometheus_enabled: false

lotus_ipfs_gateway: https://proofs.filecoin.io/ipfs/
lotus_user: "fc"
lotus_user_uid: "532"
sector_size: 34359738368
filebeat_additional_processors: |
  - drop_event:
      when:
        regexp:
          message: "^received message from router graylisted peer"
