image:
  tag: mainnet-v1.14.2

prometheusOperatorServiceMonitor: true

resources:
  requests:
    memory: 60Gi

nodeSelector:
  "fil-infra.protocol.ai/node-type": "lotus-standard"

importSnapshot:
  enabled: true
  strategy: url

persistence:
  datastore:
    enabled: true
    easyReset: true
    size: "2000Gi"
    storageClassName: "gp2"

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json

disputer:
  enabled: true
  walletAddr: f1vkujr5ecab5t6nkstqukbt2vv2ams55pwl3crki
  env:
    - name: GOLOG_LOG_FMT
      value: json

additionalLabels:
  network: mainnet
