image:
  tag: mainnet-v1.15.1@sha256:bc14d52ee5de4ab36897f3e0c0cba0dc55fa22a8bd5910ae5bc2ba826dcc1186

prometheusOperatorServiceMonitor: true

resources:
  requests:
    memory: 60Gi

nodeSelector:
  "fil-infra.protocol.ai/node-type": "lotus-standard"

importSnapshot:
  enabled: true
  claimName: chain-exports
  network: mainnet
  exportRelease: finality-stateroots
  exitCodeOnMissing: 1

persistence:
  datastore:
    enabled: true
    easyReset: true
    size: "2000Gi"
    storageClassName: "gp2"

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json

disputer:
  enabled: true
  walletAddr: f1vkujr5ecab5t6nkstqukbt2vv2ams55pwl3crki
  env:
    - name: GOLOG_LOG_FMT
      value: json

additionalLabels:
  network: mainnet
