secrets:
  libp2p:
    enabled: true
    secretName: disputer-1-libp2p-secrets
    libp2p_key: libp2p-host
  jwt:
    enabled: true
    secretName: disputer-1-jwt-secrets

loadBalancer:
  enabled: false
