image:
  repo: coryschwartz/tweety
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-realm: Filecoin Infrastructure Team
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-secret-type: auth-file
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: lb.mainnet-us-east-2-dev.fildevops.net
      paths:
        - path: /tweety(/|$)(.*)
