application:
  name: "gateway-monitor"
  labels: []
  replicas: 1
  container:
    name: application
    env: 
      - name: GOLOG_LOG_LEVEL
        value: info
      - name: GATEWAY_MONITOR_IPFS
        value: /ip4/127.0.0.1/tcp/5001/http
    resources: {}
    ports:
      - containerPort: 2112
        name: monitor
  secrets: []
  configMaps: []
  services:
    - type: ClusterIP
      selector:
        app: storetheindex
        release: storetheindex-0
      ports:
        - protocol: TCP
          port: 2112
          targetPort: 2112
          name: "monitor"
  storage: []
