---
- name: Ensure authorized keys
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ item }}"
  with_file: "{{ ssh_keys_access | product(['public-keys']) | map('reverse') | map('join', '/') | list }}"
