secrets:
  libp2p:
    enabled: true
    secretName: fullnode-1-libp2p-secrets
    libp2p_key: libp2p-host
  jwt:
    enabled: true
    secretName: fullnode-1-jwt-secrets

persistence:
  datastore:
    dataSource:
      name: snapshot-datastore-volume-fullnode-2-lotus-0-1614643213
      kind: VolumeSnapshot
      apiGroup: snapshot.storage.k8s.io

