image:
  repository: public.ecr.aws/p5f3y3g5/lotus-dev
  pullPolicy: IfNotPresent
  # https://github.com/filecoin-project/lotus/pull/5808
  tag: 1324517b

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]
  [Chainstore]
    EnableSplitstore = true

secrets:
  libp2p:
    enabled: true
    secretName: fullnode-7-libp2p-secrets
    libp2p_key: libp2p-host
  jwt:
    enabled: true
    secretName: fullnode-7-jwt-secrets

apiLoadBalancer:
  enabled: true
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    external-dns.alpha.kubernetes.io/hostname: api-cc40e0-fullnode-7.mainnet.fildevops.net
    external-dns.alpha.kubernetes.io/alias: "true"
    external-dns.alpha.kubernetes.io/ttl: "60"
