---
deployments:
  # fullnodes-calibnet
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-calibnet-fullnode
    name: fullnode-0
    values:
      - base
      - fullnode-0
  # fullnodes-calibnet
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-calibnet-fullnode
    name: fullnode-1
    values:
      - base
      - fullnode-1
  # fullnodes-calibnet
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-calibnet-fullnode
    name: disputer-0
    values:
      - base
      - disputer-0
  # dealbot nerpanet
  - chart: filecoin/efs-access
    version: 0.1.0
    namespace: ntwk-nerpanet-dealbot
    name: efs-access
    values:
      - efs-access
  - chart: filecoin/lotus-fullnode
    version: 0.3.3
    namespace: ntwk-nerpanet-dealbot
    name: dealbot-fullnode-0
    values:
      - base
      - dealbot-fullnode-0
  - chart: runix/pgadmin4
    version: 1.6.1
    namespace: ntwk-nerpanet-dealbot
    name: pgadmin
    values:
      - base
  # ipfs gateway monitor
  - chart: filecoin/lotus-bundle
    version: 0.0.12
    namespace: ipfs-gateway-monitor
    name: gateway-monitor
    values:
      - base
      - gateway-monitor-0
  - chart: filecoin/lotus-fullnode
    version: 0.3.4
    namespace: ntwk-calibnet-snapshot
    name: lotus-a
    values:
      - base
  - chart: filecoin/lotus-fullnode
    version: 0.3.4
    namespace: ntwk-calibnet-snapshot
    name: lotus-b
    values:
      - base
  - chart: filecoin/lotus-fullnode
    version: 0.3.4
    namespace: ntwk-calibnet-snapshot
    name: lotus-c
    values:
      - base
  - chart: filecoin/filecoin-chain-archiver
    version: 1.0.0
    namespace: ntwk-calibnet-snapshot
    name: calibnet
    values:
      - base
  - chart: filecoin/lotus-fullnode
    version: 0.3.4
    namespace: ntwk-mainnet-snapshot
    name: lotus-a
    values:
      - base
  - chart: filecoin/lotus-fullnode
    version: 0.3.4
    namespace: ntwk-mainnet-snapshot
    name: lotus-b
    values:
      - base
  - chart: filecoin/lotus-fullnode
    version: 0.3.4
    namespace: ntwk-mainnet-snapshot
    name: lotus-c
    values:
      - base
  - chart: filecoin/filecoin-chain-archiver
    version: 1.0.0
    namespace: ntwk-mainnet-snapshot
    name: mainnet
    values:
      - base
