- include_tasks: ../../../includes/required_vars.yml

- name: Copy binary
  copy:
      src: "{{ lotus_fountain_binary_src }}"
      dest: /usr/local/bin/lotus-fountain
      owner: root
      group: root
      mode: "0755"
  when: lotus_fountain_binary_src is defined

- name: Ensure log file exists
  file:
      state: touch
      path: "{{ lotus_fountain_golog_file }}"
      owner: "{{ lotus_user }}"
      group: "{{ lotus_user }}"
      mode: "0644"

- name: Ensure serivce file
  template:
      src: ../templates/lotus-fountain.service.j2
      dest: /etc/systemd/system/lotus-fountain.service
      owner: root
      group: root
      mode: "0644"
  notify:
      - reload-fountain

- name: Ensure web folder exists
  file:
    path: /var/www/{{ lotus_fountain_server_name }}/
    state: directory
    owner: www-data
    mode: 0755

- name: Ensure maintenance page exists
  template:
    src: ../templates/maintenance.html.j2
    dest: /var/www/{{ lotus_fountain_server_name }}/index.html
    mode: 0644

- name: Ensure maintenance site available
  template:
    src: ../templates/nginx-maintenance.conf.j2
    dest: /etc/nginx/sites-available/maintenance.conf

- name: Ensure maintenance site enabled
  file:
    src: /etc/nginx/sites-available/maintenance.conf
    dest: /etc/nginx/sites-enabled/99-maintenance.conf
    state: link
  notify: reload_nginx

- name: Ensure fountain is enabled
  systemd:
    name: "lotus-fountain"
    enabled: yes

# Have to enable firewall rules so certbot can work
- name: Ensure ufw allow
  ufw:
    rule: allow
    name: "Nginx Full"

- name: Ensure https faucet
  include_tasks: cert.yml
  when: lotus_fountain_enable_https | bool == false

- name: Ensure http faucet
  include_tasks: nginx_http.yml
  when: lotus_fountain_enable_https | bool == true

- name: Ensure faucet is enabled
  file:
    src: /etc/nginx/sites-available/faucet.conf
    dest: /etc/nginx/sites-enabled/50-faucet.conf
    state: link
  notify: reload_nginx
  when: lotus_fountain_enabled | bool == true

- name: Ensure faucet http site disabled
  file:
    path: /etc/nginx/sites-enabled/50-faucet.conf
    state: absent
  notify: reload_nginx
  when: lotus_fountain_enabled | bool == false

- name: Ensure nonce fixer service
  template:
    src: ../templates/lotus-noncefix.service.j2
    dest: /etc/systemd/system/lotus-noncefix.service
    owner: root
    group: root
    mode: "0644"

- name: Ensure nonce fixer timer
  template:
    src: ../templates/lotus-noncefix.timer.j2
    dest: /etc/systemd/system/lotus-noncefix.timer
    owner: root
    group: root
    mode: "0644"

- name: Enable nonce fixer
  systemd:
    name: lotus-noncefix.timer
    daemon_reload: yes
    enabled: true
