- name: Copy binary
  copy:
      src: "{{ lotus_fountain_binary_src }}"
      dest: /usr/local/bin/lotus-fountain
      owner: root
      group: root
      mode: "0755"
  when: lotus_fountain_binary_src is defined
  notify:
      - restart-fountain

- name: Ensure log file exists
  file:
      state: touch
      path: "{{ lotus_fountain_golog_file }}"
      owner: "{{ lotus_user }}"
      group: "{{ lotus_user }}"
      mode: "0644"

- name: Ensure serivce file
  template:
      src: ../templates/lotus-fountain.service.j2
      dest: /etc/systemd/system/lotus-fountain.service
      owner: root
      group: root
      mode: "0644"
  notify:
      - reload-fountain
  when: lotus_fountain_address is defined

- name: Ensure web folder exists
  file:
    path: /var/www/{{ lotus_fountain_server_name }}/
    state: directory
    owner: www-data
    mode: 0755

- name: Ensure maintenance page exists
  template:
    src: ../templates/maintance.html.j2
    dest: /var/www/{{ lotus_fountain_server_name }}/index.html
    mode: 0644

- name: Ensure maintenance site available
  template:
    src: ../templates/faucet-http-maint.conf.j2
    dest: /etc/nginx/sites-available/maintenance.conf

- name: Ensure maintenance site enabled
  file:
    src: /etc/nginx/sites-available/maintenance.conf
    dest: /etc/nginx/sites-enabled/99-maintenance.conf
    state: link
  notify: reload_nginx

- name: Ensure http faucet
  include_tasks: nginx_http.yml
  when: lotus_fountain_enable_https is not defined

- name: Ensure fountain is enabled and started
  systemd:
    name: "lotus-fountain"
    enabled: yes
    state: started

- name: Certbot
  include_tasks: cert.yml
  when: lotus_fountain_enable_https is defined

- name: Ensure nonce fixer service
  template:
    src: ../templates/lotus-noncefix.service.j2
    dest: /etc/systemd/system/lotus-noncefix.service
    owner: root
    group: root
    mode: "0644"

- name: Ensure nonce fixer timer
  template:
    src: ../templates/lotus-noncefix.timer.j2
    dest: /etc/systemd/system/lotus-noncefix.timer
    owner: root
    group: root
    mode: "0644"

- name: enable nonce fixer
  systemd:
    name: lotus-noncefix.timer
    state: restarted
    daemon_reload: yes
    enabled: true

- set_fact:
    lotus_fountain_ufw_profile:
      name: Lotus Fountain
      value: "{{ lookup('template', '../templates/ufw.profile.j2')}}"

- set_fact:
    lotus_fountain_nginx_access_filebeat_input:
      paths:
        - "/var/log/nginx/access.log"
      fields:
        logzio_codec: plain
        type: "nginx-access"

- set_fact:
    lotus_fountain_filebeat_input:
      paths:
        - "/var/log/lotus-fountain.log"
      fields:
        logzio_codec: json
        type: "lotus-fountain"


- set_fact:
    lotus_fountain_nginx_error_filebeat_input:
      paths:
        - "/var/log/nginx/error.log"
      fields:
        logzio_codec: plain
        type: "nginx-error"

- set_fact:
    lotus_fountain_telegraf_inputs_procstat:
      - "lotus-fountain"
