- name: Register release_name
  shell: uname -r
  register: release_name

- name: Install packages
  apt:
    pkg:
      - gcc
      - "linux-headers-{{ release_name.stdout }}"
    update_cache: yes

- name: Register modinfo_nvidia
  shell: modinfo nvidia
  register: modinfo_nvidia

- name: Nvidia drivers
  block:
    - name: Download drivers
      get_url:
        url: "{{ lotus_miner_nvidia_drivers_url }}"
        dest: /tmp/nvidia-drivers
        mode: "0755"

    - name: Install drivers
      shell: /tmp/nvidia-drivers --ui=none --no-questions
      notify: reboot-system
  when: modinfo_nvidia.rc == 1

- name: Reset miner
  block:
    - name: Ensure miner stopped
      systemd:
        name: lotus-miner
        state: stopped
    - name: Remove miner repository
      file:
        path: "{{ lotus_miner_path }}"
        state: absent
  when: lotus_miner_reset == "yes"

- name: Ensure miner repository exists
  file:
    path: "{{ lotus_miner_path }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0700"

- name: Ensure LOTUS_STORAGE_PATH global env is set
  lineinfile:
    path: /etc/environment
    line: LOTUS_STORAGE_PATH="{{ lotus_miner_path }}"

- name: Ensure log file exists
  file:
    state: touch
    path: "{{ lotus_miner_golog_file }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0644"

- name: Ensure service file
  template:
    src: ../templates/lotus-miner.service.j2
    dest: /etc/systemd/system/lotus-miner.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload-miner

- name: Copy binary
  copy:
    src: "{{ lotus_miner_binary_src }}"
    dest: /usr/local/bin/lotus-storage-miner
    owner: root
    group: root
    mode: "0755"
  when: lotus_miner_copy_binary | bool
  notify:
    - restart-miner

- name: Ensure parameters are download
  shell: /usr/local/bin/lotus-storage-miner fetch-params --proving-params "{{ lotus_miner_sector_size }}"

- name: Register stat_miner_config
  stat:
    path: "{{ lotus_miner_path }}/config.toml"
  register: stat_miner_config

- name: Initialize lotus miner
  shell: /usr/local/bin/lotus-storage-miner init --genesis-miner="{{ lotus_miner_genesis_miner }}" --actor="{{ lotus_miner_addr }}" --pre-sealed-sectors="{{ lotus_miner_presealed_sectors_path }}"
  environment:
    LOTUS_PATH: "{{ lotus_path }}"
    LOTUS_STORAGE_PATH: "{{ lotus_miner_path }}"
  become: yes
  become_user: "{{ lotus_user }}"
  when: stat_miner_config.stat.exists == False

- name: Ensure service enabled
  systemd:
    name: "lotus-miner"
    enabled: yes
    state: stopped
