apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:zMSpV9Zv9pog4iW/0hVFKqDHCee5yZs1OaNshEcsg+GQ5a8TfvZxqg==,iv:4j/jzgEsGXzsfCXkvzX4FCM+aCuGJYzFinl8ALVpZKs=,tag:MmeTV31kancjH9pC/sNW6g==,type:str]
    username: ENC[AES256_GCM,data:sPFxDnbFwf+ExPetvg==,iv:mrfZRFdnj/OZSAuVrxcFG7JGCuVivu6Ps20NPEHMp1g=,tag:GYgDWlo4z2MWKpKw1BTxMQ==,type:str]
kind: Secret
metadata:
    name: github-auth
    namespace: flux-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-20T12:42:17Z"
    mac: ENC[AES256_GCM,data:cfkS8u5CxpH82TBJt2sIp2kfvFcvGv74iMm6Q+N3pv216oIJJDHkJfU4/9wvW3Cquxoq/JLtfekfpehXJYYOtPSnEObBhMtTeQF1ThpGJu/oFuabweyqNKB31GJ+8S2cjIGUKSLXp2m/NJYoJ0QkbaOTdLAqw6RHhytIYin1Hw0=,iv:XCXHFJXhFbv5qoTUVgv4oqpymKXpl/xF1fnrSiFG90I=,tag:Q2motbU1UGJ2jiaUMX4ooQ==,type:str]
    pgp:
        - created_at: "2022-07-20T12:42:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0/wsdIQ6fOrAQ//T4Hjkiqf+8gjhKM4h0ZRQRLlRfJZCmvNhcFMlgyy2Bm9
            BGcYbZk2ugFX0lsAdajfLqppy2hhkZqVYpGd4m194VHrm4/APrf30PFNMYlqznVR
            9HQqBxSYM3A+k9hpIC6Lb8pQ0ibPqLGLnKoVrBUhZj1h8KHhxzH3cGQDPmolfL49
            XbuSgvPAUuQ4VAoZ+S2dZE6CUhnL67MCF3XQ6MVA8G2loWyRPlZg/Uz045BaM0gg
            dlscjiLr0/6U33yhCQ3N+k/9dQ2f4uv58+cFdNJFaFcp3fwONsp0MXea4wTn7WB4
            1ExaB+Z4Iwn5wuem/qPHkCDmPTnivOcPHeYTyNWcL+3c3sdAID4JN0Ubt5A6BBOK
            sZAO8dwM3GE96aA3g2A87y6u5nxA45oEfaUDkBHQ9SMUIg8L24tsl6OYKSEm/vNG
            esgIXaHL2oRXsGEfkYGyRgEkKdX1ZuY+y6ddN4nlzBqn/koMpLgBC7p3h4tFQ/32
            OraIxmmvmNYA8IRlE0pkKjYvOuAno3dL2vbRzA73jFqa0ov4etOytQoDDqK44o0Y
            siD/EUQy5t+ijst7g2FUoQAdUQO00/UdHXU1tOfBhhHrymYA/rI10nJZE2xMpDs2
            khVojmIWCRuDpaopLHyFCPRLycJAvTvztRhDcTfx62WcXJNejmUXvuN/ajQTlvjU
            aAEJAhBGl3MPPHuF/LSgmWa4xoUOa7wwWZpT3QRdyvsE2bt+ZCON/Ki/wpspKAbU
            yxhEnvtezW2IKiuAFS4tYlontFFiT+uspCLabdA/dbmr+G1nySJlkIINB6QIEKZO
            4nDo9x7fLXWD
            =/1M1
            -----END PGP MESSAGE-----
          fp: BFF6F3B5DBE7E1143CC98471BA014E8FC4D56CCB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
