prometheusOperatorServiceMonitor: false

image:
  tag: mainnet-v1.5.3

resources:
  requests:
    memory: 16Gi
    cpu: 4
  limits:
    memory: 16Gi
    cpu: 8

importSnapshot:
  enabled: false
  claimName: chain-exports
  network: mainnet
  exportRelease: export-full-archive
  exitCodeOnMissing: 0

importTrustedSnapshot:
  enabled: true

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1
  - name: DISABLE_PRE_MIGRATIONS
    value: "1"

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]

additionalLabels:
  mode: open
  network: mainnet

persistence:
  journal:
    enabled: true
    size: "20Gi"
    accessModes:
      - ReadWriteOnce
    storageClassName: standard
  datastore:
    enabled: true
    # when easyReset is true, if `/var/lib/lotus/datastore/_reset` is present, all files under
    # /var/lib/lotus/datastore/ will be removed when the pod restarts.
    easyReset: true
    size: "100Gi"
    accessModes:
      - ReadWriteOnce
    storageClassName: standard
  parameters:
    enabled: true
    size: "40Gi"
    accessModes:
      - ReadWriteOnce
    storageClassName: standard
