image:
  tag: mainnet-v1.15.1@sha256:bc14d52ee5de4ab36897f3e0c0cba0dc55fa22a8bd5910ae5bc2ba826dcc1186

prometheusOperatorServiceMonitor: true

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]

resources:
  requests:
    memory: 32Gi
    cpu: 8
  limits:
    memory: 32Gi

persistence:
  datastore:
    enabled: true
    storageClassName: "ebs-csi"
    size: "2000Gi"

importSnapshot:
  enabled: true
  strategy: url

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json

additionalLabels:
  network: mainnet
