- name: Ensure dependencies are installed
  package:
    name:
      - nginx

- name: Ensure default is is not enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure cron exists to reload server configuration
  cron:
    name: "nginx server reload"
    minute: "35"
    hour: "2"
    weekday: "1"
    job: "/etc/init.d/nginx reload"

- name: Ensure nginx.conf
  copy:
    content: "{{ nginx_conf }}"
    owner: root
    group: root
    mode: "0644"
    dest: /etc/nginx/nginx.conf
