lotus_reset: no
lotus_daemon_bootstrap: true
lotus_golog_log_fmt: json
lotus_env: {}
lotus_systemd_extras: {}
lotus_p2p_port: 1347
lotus_ipfs_gateway: "https://ipfs.io/ipfs/"
lotus_import_peerkey: false
lotus_import_wallet: false
