image:
  tag: calibnet-c11a32cf6

prometheusOperatorServiceMonitor: true

resources:
  requests:
    memory: 32Gi

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1
  - name: LOTUS_JAEGER_AGENT_HOST
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP
  - name: LOTUS_JAEGER_AGENT_PORT
    value: "6831"

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]

additionalLabels:
  network: calibnet

persistence:
  datastore:
    enabled: true
    storageClassName: "gp2"
    size: "1000Gi"
