application:
  name: "storetheindex"
  labels: []
  replicas: 1
  container:
    name: application
    args: 
      - daemon
    env: []
    resources: {}
    ports:
      - containerPort: 3001
        name: ingest
      - containerPort: 3002
        name: admin
      - containerPort: 3003
        name: finder
  secrets: []
  configMaps: []
  service:
    enabled: true
    type: ClusterIP
    ports:
      - protocol: TCP
        port: 3001
        targetPort: 3001
        name: ingest
      - protocol: TCP
        port: 3002
        targetPort: 3002
        name: admin
      - protocol: TCP
        port: 3003
        targetPort: 3003
        name: finder
  ingress:
    enabled: true
    class: nginx
    annotations: {}
    httpRules:
      - host: lb.mainnet-us-east-2-dev.fildevops.net
        path: /cory/storetheindex/ingest
        servicePort: ingest
      - host: lb.mainnet-us-east-2-dev.fildevops.net
        path: /cory/storetheindex/admin
        servicePort: admin
      - host: lb.mainnet-us-east-2-dev.fildevops.net
        path: /cory/storetheindex/finder
        servicePort: finder
  storage:
    - mount: /data/storetheindex
      chownLotus: false
      volume:
        - name: shared-volume
          persistentVolumeClaim:
              claimName: storetheindex-pvc-0
