application:
  name: "storetheindex"
  labels: []
  replicas: 1
  container:
    name: application
    args: 
      - daemon
    env: []
    resources: {}
    ports:
      - containerPort: 3000
        name: finder
      - containerPort: 3001
        name: ingest
      - containerPort: 3002
        name: admin
  secrets: []
  configMaps: []
  services:
    - type: ClusterIP
      app: storetheindex
      release: storetheindex-0
      ports:
        - protocol: TCP
          port: 3002
          targetPort: 3002
          name: admin
    - type: LoadBalancer
      app: storetheindex
      release: storetheindex-0
      ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
          name: finder
        - protocol: TCP
          port: 3001
          targetPort: 3001
          name: ingest
  storage:
    - mount: /data/storetheindex
      chownLotus: false
      volume:
        - name: shared-volume
          persistentVolumeClaim:
              claimName: chain-exports
