---
- hosts: presealed_miner
  vars:
    devices: "{{ devices_name.split(';') }}"
  tasks:
    - hostname:
        name: "{{ hostname }}"
    - apt:
        update_cache: true
    - name: Find real device names from id
      shell: |
        if [ -b "{{ devices[index] }}" ]; then
          ls "{{ devices[index] }}"
        else
          volid=$(sed -r 's/-//g' <<< {{ item }})
          readlink -f /dev/disk/by-id/*${volid}
        fi
      args:
        executable: /usr/bin/bash
      loop: "{{ devices_id.split(';') }}"
      loop_control:
        index_var: index
      register: realdevices
    - include_tasks: includes/aws_volume.yml
      loop: "{{ realdevices.results | map(attribute='stdout') | list }}"
      loop_control:
        index_var: index
