---
- hosts: seeder
  vars:
    devices: "{{ devices_name.split(';') }}"
  tasks:
    - hostname:
        name: "{{ hostname }}"
    - apt:
        update_cache: true
    - name: Find real device names from id
      shell: |
        if [ -b "{{ devices[index] }}" ]; then
          ls "{{ devices[index] }}"
        else
          volid=$(sed -r 's/-//g' <<< {{ item }})
          readlink -f /dev/disk/by-id/*${volid}
        fi
      args:
        executable: /bin/bash
      loop: "{{ devices_id.split(';') }}"
      loop_control:
        index_var: index
      register: realdevices
    - name: Find real swap device name from id
      shell: |
        if [ -b "{{ swap_name }}" ]; then
          ls "{{ swap_name }}"
        else
          volid=$(sed -r 's/-//g' <<< {{ swap_id }})
          readlink -f /dev/disk/by-id/*${volid}
        fi
      args:
        executable: /bin/bash
      register: realswap
      when: swap_name is defined
    - include_tasks: includes/aws_volume.yml
      loop: "{{ realdevices.results | map(attribute='stdout') | list }}"
      loop_control:
        index_var: index
    - include_tasks: includes/aws_swap.yml
      vars:
        item: "{{ realswap.stdout }}"
      when: swap_name is defined
