---
- hosts: presealed_miners
  become: true
  module_defaults:
    package:
      force_apt_get: yes
  tasks:
    - import_tasks: includes/lotus_user.yml
    - include_role: name=common
    - include_role: name=ntp
    - include_role: name=lotus_fullnode
    - include_role: name=lotus_miner
    - include_role: name=filebeat_logz_io
      vars:
        logz_inputs:
          - "{{ lotus_fullnode_filebeat_input }}"
          - "{{ lotus_miner_filebeat_input }}"
      when:
        - lotus_fullnode_filebeat_input is defined
        - lotus_miner_filebeat_input is defined
    - include_role: name=ufw
      vars:
        ufw_profiles:
          - "{{ lotus_fullnode_ufw_profile }}"
      when:
        - lotus_fullnode_ufw_profile is defined
    - include_role: name=telegraf
      vars:
        telegraf_global_tag_groups:
          - component: presealed_miner
          - "{{ lotus_fullnode_telegraf_tags }}"
          - "{{ lotus_miner_telegraf_tags }}"
      when:
        - lotus_fullnode_telegraf_tags is defined
        - lotus_miner_telegraf_tags is defined
