---
- hosts: fountain
  vars:
    lotus_user: "lotus"
    lotus_binary_src: /tmp/lotus
    lotus_fountain_binary_src: /tmp/lotus-fountain
    lotus_golog_file: /var/log/lotus.log
    lotus_fountain_wallet: "replaceme"
    ufw_profiles:
      - "{{ lotus_fullnode_ufw_profile }}"
      - "{{ lotus_fountain_ufw_profile }}"
    logz_inputs:
      - type: log
        paths:
          - "{{ lotus_golog_file }}"
        fields:
          logzio_codec: json
          token: "{{ logz_io_shared_token }}"
          type: lotus-daemon
        fields_under_root: true
        json.keys_under_root: false
        json.message_key: msg
        encoding: utf-8
        ignore_older: 3h
  tasks:
    - name: Ensure lotus user exists
      user:
        name: "{{ lotus_user }}"
        state: present
        uid: 996
        system: yes
    - include_role:
        name: telegraf
    - include_role:
        name: filebeat_logz_io
    - include_role:
        name: lotus_fullnode
    - include_role:
        name: lotus_fountain
    - include_role:
        name: ufw
