---
- hosts: lotus_daemon
  become: true
  module_defaults:
    package:
      force_apt_get: yes
  tasks:
    - import_tasks: includes/lotus_user.yml
    - include_role: name=common
    - include_role: name=ntp
    - include_role: name=lotus_fullnode
    - include_role: name=filebeat_logz_io
      vars:
        logz_inputs:
          - "{{ lotus_fullnode_filebeat_input }}"
      when:
        - lotus_fullnode_filebeat_input is defined
    - include_role: name=ufw
      vars:
        ufw_profiles:
          - "{{ lotus_fullnode_ufw_profile }}"
      when:
        - lotus_fullnode_ufw_profile is defined
