---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    lotus_health_binary_src: /tmp/lotus-health
    lotus_health_golog_file: "/var/log/lotus-health.log"
    lotus_health_copy_binary: True
    logz_inputs:
      - type: log
        paths:
          - "{{ lotus_fullnode.lotus_golog_file }}"
        fields:
          logzio_codec: json
          token: "{{ logz_io_shared_token }}"
          type: lotus-daemon
        fields_under_root: true
        json.keys_under_root: false
        json.message_key: msg
        encoding: utf-8
        ignore_older: 3h
      - type: log
        paths:
          - "{{ lotus_health_golog_file }}"
        fields:
          logzio_codec: json
          token: "{{ logz_io_shared_token }}"
          type: lotus-health
        fields_under_root: true
        json.keys_under_root: false
        json.message_key: msg
        encoding: utf-8
        ignore_older: 3h
  tasks:
    - include_vars:
        file: roles/lotus_fullnode/defaults/main.yml
        name: lotus_fullnode
    - include_role:
        name: telegraf
    - include_role:
        name: filebeat_logz_io
    - include_role:
        name: lotus_health
