---
- hosts: faucet
  become: true
  vars:
    lotus_fountain_address: "{{ lotus_wallet_address }}"
  module_defaults:
    package:
      force_apt_get: yes
  tasks:
    - import_tasks: includes/lotus_user.yml
    - include_role: name=common
    - include_role: name=ntp
    - include_role: name=lotus_fountain
    - include_role: name=filebeat_logz_io
      vars:
        logz_inputs:
          - "{{ lotus_fullnode_filebeat_input }}"
      when:
        - lotus_fullnode_filebeat_input is defined
    - include_role: name=ufw
      vars:
        ufw_profiles:
          - "{{ lotus_fountain_ufw_profile }}"
      when:
        - lotus_fountain_ufw_profile is defined
    - include_role: name=telegraf
      vars:
        telegraf_global_tag_groups:
          - component: fountain
        telegraf_inputs_procstat:
          - "{{ lotus_fullnode_telegraf_inputs_procstat }}"
          - "{{ lotus_fountain_telegraf_inputs_procstat }}"
