---
- hosts: presealers
  become: true
  module_defaults:
    package:
      force_apt_get: yes
  tasks:
    - import_tasks: includes/lotus_user.yml
    - include_role: name=common
    - include_role: name=ntp
    - include_role: name=lotus_seed
    - include_role: name=filebeat_logz_io
      vars:
        logz_inputs:
          - "{{ lotus_seed_filebeat_input }}"
      when:
        - lotus_seed_filebeat_input is defined
    - include_role: name=telegraf
      vars:
        telegraf_global_tag_groups:
          - component: presealer
          - "{{ lotus_seed_telegraf_tags }}"
      when:
        - lotus_seed_telegraf_tags is defined
