---
all:
  children:
    aws:
      vars:
        ansible_user: ubuntu
      children:
        presealers:
          hosts:
            t0201w0.seeder.fil-test.net:
            t0201w1.seeder.fil-test.net:
            t0201w2.seeder.fil-test.net:
            t0201w3.seeder.fil-test.net:
            t0201w4.seeder.fil-test.net:
