image:
  # master build (after v1.14.0 merge; v1.14.0 does not contain splitstore sort stuff)
  tag: mainnet-949a04643

prometheusOperatorServiceMonitor: true

importSnapshot:
  enabled: true
  strategy: url

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json

additionalLabels:
  network: mainnet
