persistence:
  datastore:
    enabled: true
    storageClassName: "ebs-csi"
    size: "1000Gi"

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]
  [Chainstore]
    EnableSplitstore = true
  [Chainstore.Splitstore]
    ColdStoreType = "discard"
    MarkSetType = "badger"
    HotStoreFullGCFrequency = 6
