controller: 
  enabled: true
  postgres:
    enabled: true
  ingress:
    enabled: true
    annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/auth-realm: Filecoin Infrastructure Team
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-secret-type: auth-file
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: lb.mainnet-us-east-2-dev.fildevops.net
        paths:
         - path: /mainnet-dealbot-controller(/|$)(.*)
  secrets:
    keySecret: dealbot-controller-key
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 500Mi

postgres:
  enabled: true
  instances: 1
  version: 13
  teamid: dealbotteam
  user: dealbotuser
  database: dealbotdb
  volume: 100Gi
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 500Mi

daemon:
  enabled: true
  replicas: 1
  lotusAPI:
    lotusAPITokenSecret: "fullnode-0-jwt-secrets"
    lotusAPIMultiaddr: "/dns/dealbot-fullnode-0-lotus-daemon/tcp/1234/p2p/12D3KooWDxZrDEfnPq3CEWfXL8W5xG6yr2nZcwE1yShv3KatZXt6"
    wallet: f3xg5otbsfffe7zvj45wyn6qxwbw3m4eghwj77c72hkqg7pzzgzbwoiskasnmumar553zcl5rxdrp7ec7rm4fa
  persistence:
    enabled: true
    claimName: chain-exports
    mountPath: /efs
    data: /efs/dealbot/mainnet/data
    nodedata: /efs/dealbot/mainnet/nodedata
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
