apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"eniconfigs.crd.k8s.amazonaws.com"},"spec":{"group":"crd.k8s.amazonaws.com","names":{"kind":"ENIConfig","plural":"eniconfigs","singular":"eniconfig"},"preserveUnknownFields":false,"scope":"Cluster","versions":[{"name":"v1alpha1","schema":{"openAPIV3Schema":{"type":"object","x-kubernetes-preserve-unknown-fields":true}},"served":true,"storage":true}]}}
  creationTimestamp: "2022-12-02T03:50:11Z"
  generation: 1
  name: eniconfigs.crd.k8s.amazonaws.com
  resourceVersion: "276"
  uid: b637ee54-4e0b-4c20-a182-1d82bd36cdc3
spec:
  conversion:
    strategy: None
  group: crd.k8s.amazonaws.com
  names:
    kind: ENIConfig
    listKind: ENIConfigList
    plural: eniconfigs
    singular: eniconfig
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
status:
  acceptedNames:
    kind: ENIConfig
    listKind: ENIConfigList
    plural: eniconfigs
    singular: eniconfig
  conditions:
  - lastTransitionTime: "2022-12-02T03:50:11Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-12-02T03:50:11Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
