controller: 
  enabled: false
postgres:
  enabled: false

daemon:
  enabled: true
  replicas: 1
  lotusAPI:
    lotusAPITokenSecret: "fullnode-1-jwt-secrets"
    lotusAPIMultiaddr: "/dns/dealbot-fullnode-1-lotus-daemon/tcp/1234/p2p/12D3KooWFX36AfFhL6949FDDjHDW7VJsr1f19brTrZxHBCz28ks2"
    wallet: f1wdxdpqh3hirrhp353i4o6ld7bsw6evh3v7i5jtq
  persistence:
    enabled: true
    claimName: chain-exports
    mountPath: /efs
    data: /efs/dealbot/mainnet/nodedata
    nodedata: /efs/dealbot/mainnet/nodedata
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
