- name: Install packages
  apt:
    pkg:
      - mesa-opencl-icd
      - ocl-icd-opencl-dev
      - ntp
    update_cache: yes

- name: Ensure ntp service enabled & started
  systemd:
    name: "ntp"
    enabled: yes
    state: started

- name: Reset lotus
  block:
    - name: Ensure lotus stopped
      systemd:
        name: lotus-daemon
        state: stopped
    - name: Remove lotus repository
      file:
        path: "{{ lotus_path }}"
        state: absent
  when: lotus_reset == "yes"

- name: Ensure lotus repository exists
  file:
    path: "{{ lotus_path }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0700"

- name: Ensure LOTUS_PATH global env is set
  lineinfile:
    path: /etc/environment
    line: LOTUS_PATH="{{ lotus_path }}"

- name: Ensure proof parameters directory exists
  file:
    path: "{{ lotus_proof_params_path }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0700"

- name: Ensure log file exists
  file:
    state: touch
    path: "{{ lotus_golog_file }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0644"

- name: Ensure service file
  template:
    src: ../templates/lotus-daemon.service.j2
    dest: /etc/systemd/system/lotus-daemon.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload-lotus

- name: Copy binary
  copy:
    src: "{{ lotus_binary_src }}"
    dest: /usr/local/bin/lotus
    owner: root
    group: root
    mode: "0755"
  when: lotus_copy_binary | bool

- name: Ensure lotus configuration
  template:
    src: ../templates/config.toml.j2
    dest: "{{ lotus_path }}/config.toml"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0644"

- name: Ensure lotus peerkey
  block:
    - name: Ensure keystore path created
      file:
        path: "{{ lotus_path }}/keystore/"
        state: directory
        owner: "{{ lotus_user }}"
        group: "{{ lotus_user }}"
        mode: "0700"
    - name: Ensure peerkey exists
      copy:
        content: "{{ lotus_libp2p_keyinfo }}"
        owner: "{{ lotus_user }}"
        group: "{{ lotus_user }}"
        mode: "0600"
        dest: "{{ lotus_path }}/keystore/{{ lotus_libp2p_keyname }}"
  when: lotus_libp2p_keyinfo is defined

- name: Ensure lotus service enabled & started
  systemd:
    name: "lotus-daemon"
    enabled: yes
    state: started

- set_fact:
    lotus_fullnode_ufw_profile:
      name: Lotus Daemon
      value: "{{ lookup('template', '../templates/ufw.profile.j2')}}"
