image:
  pullPolicy: Always
  tag: "1.1.0"

indexResolver:
  replicas: 3
  s3Resolver:
    bucket: "filecoin-snapshots-mainnet-staging"
    endpoint: "https://eafecb340a3ce23027e1eba779ed4d91.r2.cloudflarestorage.com"
    secretName: r2-access
  additionalEnv:
  - name: "GOLOG_LOG_FMT"
    value: "json"

  loadBalancer:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:657871693752:certificate/3698ebd6-d04a-4354-91da-7da14c11c611
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      external-dns.alpha.kubernetes.io/hostname: snapshots.mainnet.fildevops.net
      external-dns.alpha.kubernetes.io/alias: "true"
      external-dns.alpha.kubernetes.io/ttl: "60"

snapshots:
  nodes:
  - /dns/lotus-a-lotus-daemon/tcp/1234
  - /dns/lotus-b-lotus-daemon/tcp/1234
  - /dns/lotus-c-lotus-daemon/tcp/1234

  schedule: "0 */2 * * *"

  interval: "240"
  confidence: "30"

  activeDeadlineSeconds: 10800

  uploads:
    enabled: true
    bucket: "filecoin-snapshots-mainnet-staging"
    endpoint: "https://eafecb340a3ce23027e1eba779ed4d91.r2.cloudflarestorage.com"
    secretName: r2-access

  jwtTokens:
    secretName: lotus-jwt

  additionalEnv:
  - name: "FCA_CREATE_RETRIEVAL_ENDPOINT_PREFIX"
    value: "https://pub-125dc2d5e54f44e4af7593c5b2985ec1.r2.dev"
  - name: "GOLOG_LOG_FMT"
    value: "json"
  - name: "FCA_CREATE_PROGRESS_UPDATE"
    value: "60s"
  - name: "FCA_CREATE_NAME_PREFIX"
    value: "minimal/"

nodelocker:
  additionalEnv:
  - name: "GOLOG_LOG_FMT"
    value: "json"
