- name: Ensure dependencies are installed
  package:
    name:
      - software-properties-common

- name: Add certbot ppa
  apt_repository:
    repo: ppa:certbot/certbot

- name: Update apt cache
  apt:
    update_cache: true

- name: Install certbot
  package:
    name:
      - certbot
      - python3-certbot-nginx
