name: Flux-image-updates auto PR
on:
  push:
    branches:
    - releases/flux-image-updates

jobs:
  verify-kustomize:
    name: Verify Kustomizations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - name: verify-kustomize
      run: ./scripts/verify_kustomize.bash

  open-pr:
    name: Create PR
    runs-on: ubuntu-latest
    needs: verify-kustomize
    steps:
    - uses: actions/checkout@v2
      name: checkout
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.3
      id: open-pr
      with:
        branch: releases/flux-image-updates
        base: master
        title: "Pulling ${{ github.ref }} into master"
        body: |
          🐳 Auto image update
        labels: "flux-image-automation,automerge"
        token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: true

    # - name: Approve Pull Request
        # needs: open-pr
    #   uses: juliangruber/approve-pull-request-action@v2.0.0
    #     with:
    #       github-token: ${{ secrets.GITHUB_TOKEN }}
    #       number: ${{ steps.open-pr.pull-request-number }}
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.open-pr.pull-request-number }}
        method: rebase
