name: Flux-image-updates auto PR
on:
  push:
    branches:
    - releases/flux-image-updates

jobs:
  verify-kustomize:
    name: Verify Kustomizations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - name: verify-kustomize
      run: ./scripts/verify_kustomize.bash

  open-pr:
    name: Create PR
    runs-on: ubuntu-latest
    needs: verify-kustomize
    steps:
    - uses: actions/checkout@v2
      name: checkout
      with:
        fetch-depth: 0
    - name: Create Pull Request
      uses: GlacierWalrus/action-pull-request@v0.5.4
      id: create-pr
      with:
        source_branch: releases/flux-image-updates
        target_branch: master
        title: "Pulling ${{ github.ref }} into master"
        body: |
          🐳 Auto image update
        label: "flux-image-automation,automerge"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Approve Pull Request
        # needs: open-pr
    #   uses: juliangruber/approve-pull-request-action@v2.0.0
    #     with:
    #       github-token: ${{ secrets.GITHUB_TOKEN }}
    #       number: ${{ steps.open-pr.pull-request-number }}

    - name: automerge
      needs: verify-kustomize
      uses: pascalgn/automerge-action@v0.15.5
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "flux-image-automation,automerge"
        MERGE_FILTER_AUTHOR: fil-infra-bot
        PULL_REQUEST: ${{ steps.create-pr.outputs.pr_number }}
        # This retry config allows time for merge checks to run
        MERGE_RETRY_SLEEP: 10000 # 10s in milliseconds
        MERGE_RETRIES: 6