---
name: trigger-lotus-rollout
on:
  workflow_dispatch:
    inputs:
      override_tag:
        description: "lotus tag"
      slack_channel:
        description: "the slack channel where notifications are sent"
        default: "netops-circleci-test"
      circle_branch:
        description: "circleci branch (used for testing new lotus-infra deploy code)"
        default: master

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLE_TOKEN }}
          project-slug: filecoin-project/lotus-infra
          branch: ${{ github.event.inputs.circle_branch }}
          payload: |
            {
              "override_tag": "${{ github.event.inputs.override_tag }}",
              "slack_channel": "${{ github.event.inputs.slack_channel }}"
            }
