---
name: trigger-helm-deploy
on:
  workflow_dispatch:
    # Warn: workflow_dispatch events take a maximum of 10 inputs
    inputs:
      circle_context:
        description: "CI context for aws credentials"
        default: "sentinel-staging-deploy"
      kubernetes_cluster:
        description: "kubernetes cluster"
        default: "mainnet-us-east-2-dev-eks"
      aws_region:
        description: "aws region"
        default: "us-east-2"
      namespace:
        description: "kubernetes namespace"
        default: "ntwk-butterfly-fullnode"
      release:
        description: "helm release"
        default: "fullnode-0"
      chart:
        description: "the helm chart"
        default: "filecoin/lotus-fullnode"
      chart_version:
        description: "the helm chart version"
        default: "0.3.2"
      helm_append:
        description: "append this to the end of the helm command (i.e to add more -set's)"
      override_repository:
        description: "helm chart image.repository"
      override_tag:
        description: "helm chart image.tag"

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLE_TOKEN }}
          project-slug: filecoin-project/lotus-infra
          branch: master
          payload: |
            {
              "api_workflow_requested": "helm-deploy",
              "circle_context": "${{ github.event.inputs.circle_context }}",
              "kubernetes_cluster": "${{ github.event.inputs.kubernetes_cluster }}",
              "aws_region": "${{ github.event.inputs.aws_region }}",
              "namespace": "${{ github.event.inputs.namespace }}",
              "release": "${{ github.event.inputs.release }}",
              "chart": "${{ github.event.inputs.chart }}",
              "chart_version": "${{ github.event.inputs.chart_version }}",
              "helm_append": "${{ github.event.inputs.helm_append }}",
              "override_repository": "${{ github.event.inputs.override_repository }}",
              "override_tag": "${{ github.event.inputs.override_tag }}",
              "slack_channel": "netops-circleci-test"
            }
