apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/applications/fullnode


configMapGenerator:
- files:
  - values.yaml=values.yaml
  name: fullnode-network-common
